DELETE FROM "SNET_PROJECT"."snet.database.tables::MANAGER";
INSERT INTO "SNET_PROJECT"."snet.database.tables::MANAGER" VALUES(1,'HR','arun@sap.com','ICD','ARUN','9534221441');
INSERT INTO "SNET_PROJECT"."snet.database.tables::MANAGER" VALUES(2,'IOT','dev@sap.com','ICM','DEV','9235324671');
INSERT INTO "SNET_PROJECT"."snet.database.tables::MANAGER" VALUES(3,'MARKETING','bijoyan@sap.com','ADF','BIJOYAN','9756324575');
INSERT INTO "SNET_PROJECT"."snet.database.tables::MANAGER" VALUES(4,'PROCUREMENT','prodipto@sap.com','FGY','PRODIPTO','9875687654');
INSERT INTO "SNET_PROJECT"."snet.database.tables::MANAGER" VALUES(5,'SALES','sachin@sap.com','WER','SACHIN','8364852756');
INSERT INTO "SNET_PROJECT"."snet.database.tables::MANAGER" VALUES(6,'SUSTAINABILITY','katrina@sap.com','TYH','KATRINA','9864563745');
INSERT INTO "SNET_PROJECT"."snet.database.tables::MANAGER" VALUES(7,'SCM','deepika@sap.com','HNJ','DEEPIKA','8643679747');


delete from "SNET_PROJECT"."snet.database.tables::SCHOLAR";
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(1,1,'BOUDHAYAN',TO_DATE('23-02-1996', 'DD-MM-YYYY'),'boudhayan@sap.com',9546321223);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(2,3,'RANBIR',TO_DATE('23-02-1994', 'DD-MM-YYYY'),'ranbir@sap.com',9124224643);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(3,2,'JOHN',TO_DATE('21-04-1996', 'DD-MM-YYYY'),'john@sap.com',8746321223);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(4,3,'BALAJI',TO_DATE('12-12-1986', 'DD-MM-YYYY'),'balaji@sap.com',9446821225);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(5,6,'SYED',TO_DATE('25-02-1986', 'DD-MM-YYYY'),'syed@sap.com',9865895389);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(6,7,'GEORGE',TO_DATE('12-01-2001', 'DD-MM-YYYY'),'george@sap.com',8174523670);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(7,1,'STEVE',TO_DATE('11-02-1992', 'DD-MM-YYYY'),'steve@sap.com',954562233);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(8,4,'PREETI',TO_DATE('02-02-1999', 'DD-MM-YYYY'),'preeti@sap.com',9475328960);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(9,5,'JENNIFER',TO_DATE('12-11-1976', 'DD-MM-YYYY'),'jennifer@sap.com',9345621346);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(10,5,'SAM',TO_DATE('18-05-2006', 'DD-MM-YYYY'),'sam@sap.com',9123456234);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(11,2,'SULLIVAN',TO_DATE('28-09-2001', 'DD-MM-YYYY'),'sullivan@sap.com',9819054223);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(12,6,'RITIKA',TO_DATE('23-02-2000', 'DD-MM-YYYY'),'ritika@sap.com',9657399246);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(13,3,'MODI',TO_DATE('13-03-1987', 'DD-MM-YYYY'),'modi@sap.com',8164928590);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(14,7,'RAHUL',TO_DATE('19-02-1987', 'DD-MM-YYYY'),'rahul@sap.com',9278539562);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR" VALUES(15,4,'KEJRIWAL',TO_DATE('16-07-1999', 'DD-MM-YYYY'),'kejriwal@sap.com',8174859353);


delete from "SNET_PROJECT"."snet.database.tables::EMPLOYEE";
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (1,1,'shakti@sap.com','SHAKTI',TO_DATE('21-02-1991','DD-MM-YYYY'),9873527463);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (2,2,'khan@sap.com','KHAN',TO_DATE('22-02-1992','DD-MM-YYYY'),8162845281);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (3,3,'singh@sap.com','SINGH',TO_DATE('23-03-1993','DD-MM-YYYY'),9745284621);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (4,4,'das@sap.com','DAS',TO_DATE('12-12-1992','DD-MM-YYYY'),9735678901);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (5,5,'gupta@sap.com','GUPTA',TO_DATE('11-03-1991','DD-MM-YYYY'),8787652781);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (6,6,'sharma@sap.com','SHARMA',TO_DATE('24-04-1993','DD-MM-YYYY'),8725423452);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (7,7,'iyer@sap.com','IYER',TO_DATE('10-02-1994','DD-MM-YYYY'),9187354321);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (8,2,'swamy@sap.com','SWAMY',TO_DATE('09-02-1994','DD-MM-YYYY'),8907865431);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (9,3,'trump@sap.com','TRUMP',TO_DATE('15-05-1995','DD-MM-YYYY'),9879235212);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (10,4,'putin@sap.com','PUTIN',TO_DATE('19-05-1994','DD-MM-YYYY'),9089786754);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (11,5,'kapoor@sap.com','KAPOOR',TO_DATE('11-06-1996','DD-MM-YYYY'),8978212345);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (12,6,'murugan@sap.com','MURUGAN',TO_DATE('09-01-1996','DD-MM-YYYY'),9087654789);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (13,7,'amar@sap.com','AMAR',TO_DATE('08-08-1992','DD-MM-YYYY'),8178907658);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE" VALUES (14,1,'akbar@sap.com','AKBAR',TO_DATE('14-08-1993','DD-MM-YYYY'),8178908965);


DELETE FROM "SNET_PROJECT"."snet.database.tables::SKILLS";
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(1,'PYTHON');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(2,'JAVA');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(3,'JAVASCRIPT');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(4,'HASKELL');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(5,'RUBY');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(6,'HANA');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(7,'SAC');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(8,'ML');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(9,'ANGULAR');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(10,'NODEJS');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(11,'C++');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(12,'PHP');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(13,'DJANGO');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(14,'LARAVEL');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(15,'REACTJS');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(16,'DEVOPS');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(17,'C#');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(18,'ANDROID');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(19,'IOS');
INSERT INTO "SNET_PROJECT"."snet.database.tables::SKILLS" VALUES(20,'SQL');


DELETE FROM "SNET_PROJECT"."snet.database.tables::JOBS";
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOBS" VALUES(1,1,TO_DATE('21-08-2018','DD-MM-YYYY'),TO_DATE('11-05-2019','DD-MM-YYYY'),'DESCRIPTION 1',2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOBS" VALUES(2,2,TO_DATE('12-09-2018','DD-MM-YYYY'),TO_DATE('12-03-2019','DD-MM-YYYY'),'DESCRIPTION 2',2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOBS" VALUES(3,3,TO_DATE('14-08-2018','DD-MM-YYYY'),TO_DATE('16-04-2019','DD-MM-YYYY'),'DESCRIPTION 3',2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOBS" VALUES(4,4,TO_DATE('19-10-2018','DD-MM-YYYY'),TO_DATE('17-06-2019','DD-MM-YYYY'),'DESCRIPTION 4',2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOBS" VALUES(5,5,TO_DATE('11-08-2018','DD-MM-YYYY'),TO_DATE('18-06-2019','DD-MM-YYYY'),'DESCRIPTION 5',2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOBS" VALUES(6,6,TO_DATE('01-09-2018','DD-MM-YYYY'),TO_DATE('12-05-2019','DD-MM-YYYY'),'DESCRIPTION 6',2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOBS" VALUES(7,7,TO_DATE('12-10-2018','DD-MM-YYYY'),TO_DATE('19-04-2019','DD-MM-YYYY'),'DESCRIPTION 7',2);


DELETE FROM "SNET_PROJECT"."snet.database.tables::PAST_RECORDS";
INSERT INTO "SNET_PROJECT"."snet.database.tables::PAST_RECORDS" VALUES(TO_DATE('21-08-2018','DD-MM-YYYY'),TO_DATE('11-05-2019','DD-MM-YYYY'),1,1,1);
INSERT INTO "SNET_PROJECT"."snet.database.tables::PAST_RECORDS" VALUES(TO_DATE('12-09-2018','DD-MM-YYYY'),TO_DATE('12-03-2019','DD-MM-YYYY'),3,2,2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::PAST_RECORDS" VALUES(TO_DATE('14-08-2018','DD-MM-YYYY'),TO_DATE('16-04-2019','DD-MM-YYYY'),4,3,3);
INSERT INTO "SNET_PROJECT"."snet.database.tables::PAST_RECORDS" VALUES(TO_DATE('01-09-2018','DD-MM-YYYY'),TO_DATE('12-05-2019','DD-MM-YYYY'),5,6,6);
INSERT INTO "SNET_PROJECT"."snet.database.tables::PAST_RECORDS" VALUES(TO_DATE('12-10-2018','DD-MM-YYYY'),TO_DATE('19-04-2019','DD-MM-YYYY'),10,7,7);
INSERT INTO "SNET_PROJECT"."snet.database.tables::PAST_RECORDS" VALUES(TO_DATE('11-08-2018','DD-MM-YYYY'),TO_DATE('18-06-2019','DD-MM-YYYY'),7,5,5);
INSERT INTO "SNET_PROJECT"."snet.database.tables::PAST_RECORDS" VALUES(TO_DATE('01-09-2018','DD-MM-YYYY'),TO_DATE('12-05-2019','DD-MM-YYYY'),14,6,6);

DELETE FROM "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS";
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,1,1,1);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,2,2,2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,3,3,3);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,4,4,4);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,5,5,5);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,6,6,6);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,7,7,7);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,8,8,8);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(5,9,9,9);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,10,10,10);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,11,11,11);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(9,12,12,12);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(5,13,13,13);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,14,14,14);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,1,15,15);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,2,16,16);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,3,17,17);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,4,18,18);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,5,19,19);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,6,20,20);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,7,1,21);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,8,3,22);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,9,2,23);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(9,10,3,24);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,11,4,25);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,12,5,26);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(6,13,6,27);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,14,8,28);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(8,15,8,29);
INSERT INTO "SNET_PROJECT"."snet.database.tables::SCHOLAR_SKILLS" VALUES(7,15,7,30);


DELETE FROM "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS";
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(7,1,1,1);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(7,2,2,2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,3,3,3);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,4,4,4);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(9,5,5,5);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(9,6,6,6);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(7,7,7,7);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(7,8,8,8);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,9,9,9);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,10,10,10);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(9,11,11,11);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(9,12,12,12);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,13,13,13);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,14,14,14);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(9,1,15,15);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(9,2,16,16);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,3,17,17);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(8,4,18,18);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(7,5,19,19);
INSERT INTO "SNET_PROJECT"."snet.database.tables::EMPLOYEE_SKILLS" VALUES(7,6,20,20);


DELETE FROM "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT";
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (1,1,1);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (2,2,2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (3,3,3);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (4,4,4);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (5,5,5);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (6,6,6);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (7,7,7);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (8,1,8);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (9,2,9);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (10,3,12);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (11,4,13);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (12,5,14);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (13,6,15);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_SKILLS_REQUIREMENT" VALUES (14,7,16);


DELETE FROM "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION";
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(1,TO_DATE('10-08-2018','DD-MM-YYYY'),1,1 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(2,TO_DATE('09-08-2018','DD-MM-YYYY'),2,2);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(3,TO_DATE('10-08-2018','DD-MM-YYYY'),3,3);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(4,TO_DATE('10-08-2018','DD-MM-YYYY'),4,4);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(5,TO_DATE('09-08-2018','DD-MM-YYYY'),5,5 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(6,TO_DATE('08-08-2018','DD-MM-YYYY'),6,6);
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(7,TO_DATE('08-08-2018','DD-MM-YYYY'),7,7 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(8,TO_DATE('09-08-2018','DD-MM-YYYY'),8,1 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(9,TO_DATE('09-08-2018','DD-MM-YYYY'),9,2 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(10,TO_DATE('10-08-2018','DD-MM-YYYY'),10,3 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(11,TO_DATE('10-08-2018','DD-MM-YYYY'),11,4 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(12,TO_DATE('08-08-2018','DD-MM-YYYY'),12,5 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(13,TO_DATE('09-08-2018','DD-MM-YYYY'),13,6 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(14,TO_DATE('08-08-2018','DD-MM-YYYY'),14,7 );
INSERT INTO "SNET_PROJECT"."snet.database.tables::JOB_APPLICATION" VALUES(15,TO_DATE('08-08-2018','DD-MM-YYYY'),15,2 );
